{{- if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "service-chart.fullname" . }}-scaledobject
  labels:
    {{- include "service-chart.standardLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "service-chart.fullname" . }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  triggers:
    - type: memory
      metadata:
        type: Utilization
        value: "{{ .Values.autoscaling.triggers.memory.value }}"
{{- end }}
