apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "service-chart.fullname" . }}
  labels:
    {{- include "service-chart.standardLabels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "service-chart.selectorLabels" . | nindent 6  }}
  strategy:
    blueGreen:
      activeService: {{ include "service-chart.fullname" . }}
      previewService: {{ include "service-chart.fullname" . }}-preview
  template:
    metadata:
      labels:
        app: {{ include "service-chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path | default "/" }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 10 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path | default "/" }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path | default "/" }}
              port: http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds | default 10 }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold | default 30 }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
