{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "service-chart.fullname" . }}
  labels:
    {{- include "service-chart.standardLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "service-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: 30s
{{- end }}
