apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-chart.fullname" . }}
  labels:
    {{- include "service-chart.standardLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "service-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-chart.fullname" . }}-preview
  labels:
    {{- include "service-chart.standardLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "service-chart.selectorLabels" . | nindent 4 }}
