fullnameOverride: ""

deploymentAnnotations: {}
  # example: "annotation"

replicaCount: 3

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

pdb:
  maxUnavailable: 1

image:
  repository: hanselchristopher001/password-generator
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

nodeSelector: {}
affinity: {}
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/os
  #         operator: In
  #         values:
  #         - linux
tolerations: {}

probes:
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 5
  startup:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 20
    failureThreshold: 10

service:
  type: ClusterIP
  port: 80

containerPort: 5000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /generate-passwords
          pathType: Prefix
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  triggers:
    memory:
      value: "80"

serviceMonitor:
  enabled: true

topologySpreadConstraints:
  # - maxSkew: 1
  #   topologyKey: kubernetes.io/hostname
  #   whenUnsatisfiable: ScheduleAnyway
  #   labelSelector:
  #     matchExpressions:
  #     - key: disktype
  #       operator: In
  #       values:
  #       - ssd
  # - maxSkew: 1
  #   topologyKey: topology.kubernetes.io/zone
  #   whenUnsatisfiable: ScheduleAnyway
  #   labelSelector:
  #     matchExpressions:
  #     - key: disktype
  #       operator: In
  #       values:
  #       - ssd
