fullnameOverride: ""

replicaCount: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  triggers:
    memory:
      value: "80"

pdb:
  maxUnavailable: 1

topologySpreadConstraints:
  # - maxSkew: 1
  #   topologyKey: kubernetes.io/hostname
  #   whenUnsatisfiable: ScheduleAnyway
  #   labelSelector:
  #     matchExpressions:
  #     - key: disktype
  #       operator: In
  #       values:
  #       - ssd
  # - maxSkew: 1
  #   topologyKey: topology.kubernetes.io/zone
  #   whenUnsatisfiable: ScheduleAnyway
  #   labelSelector:
  #     matchExpressions:
  #     - key: disktype
  #       operator: In
  #       values:
  #       - ssd

# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       —matchExpressions:
#         —key: "disktype"
#           operator: "In"
#           values:
#           — ssd


image:
  repository: hanselchristopher001/password-generator
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

resources: {}

nodeSelector: {}
affinity: {}
tolerations: {}

probes:
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 20
    periodSeconds: 5
  startup:
    enabled: true
    path: "/"
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 10

service:
  type: ClusterIP
  port: 80

containerPort: 5000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceMonitor:
  enabled: true
